# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventario', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=200)),
                ('CI', models.CharField(max_length=200)),
                ('fecha_devolucion', models.DateTimeField(verbose_name='fecha devolucion')),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=200)),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('fecha_de_ingreso', models.DateTimeField(verbose_name='fecha ingreso')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=200)),
                ('CI', models.CharField(max_length=200)),
                ('fecha_comienzo', models.DateTimeField(verbose_name='fecha comienzo')),
                ('fecha_fin', models.DateTimeField(verbose_name='fecha fin')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CI', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='copia',
            name='ISBN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblio.Libro'),
        ),
    ]
