# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devolucion',
            name='fecha_devolucion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='libro',
            name='fecha_de_ingreso',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_comienzo',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_fin',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='socio',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_nacimiento',
            field=models.DateTimeField(),
        ),
    ]
